### ISSUE TITLE
It does not handle escape backslash for class names correctly

### ISSUE THREAD

**Issue by AcrylicShrimp** [dperini/nwsapi#52] opened 2021-12-07 15:37 UTC
Hello! Thanks for this amazing work!

I found that the `nwsapi` tries to select pseudo-classes when the given class name includes `:` with preceding `\`. And this naming pattern is used by famous CSS library `tailwindCSS`. Is there way to handle correctly?

Thank you!

**Comment by dperini** [comment] 2023-04-06 15:19
@AcrylicShrimp 
no, I don't think this is possible and I also believe it is wrong.
In CSS the colon : is the opening character of a named pseudo-class.
Escaping the colon : is changing the meaning of it and its associated name.
No issue here ... closing it. Please use a forum not a bug report.

**Closed by dperini** 2023-04-06 15:19 UTC
