### ISSUE TITLE
v2.2.1 causing "Octal escape sequences are not allowed in strict mode."

### ISSUE THREAD

**Issue by terwort** [dperini/nwsapi#58] opened 2022-06-29 20:47 UTC
My jest tests randomly started failing with this error since it is a dependency on jsdom. After installing nwsapi directly into my project and setting to v2.2.0, it is now fixed. Could someone please hotfix this issue so I can remove the dependency directly from my project?

![Screen Shot 2022-06-29 at 3 44 57 PM](https://user-images.githubusercontent.com/37204984/176541232-08950fe7-d49a-467a-af98-11fbbf32b93c.png)

**Comment by dperini** [comment] 2023-04-06 14:39
@terwort 
I am closing this because thhere is no reproducible test case accompanying the description of the bug.
Feel free to reopen this if you can provide such test code.

**Closed by dperini** 2023-04-06 14:39 UTC
