### ISSUE TITLE
Support for :scope

### ISSUE THREAD

**Issue by rraziel** [dperini/nwsapi#4] opened 2017-11-26 16:40 UTC
Hello,

More a question than an issue: I'm going to take a look at adding tests for the `:scope` pseudo-class - cf. tmpvar/jsdom#2028 - however from what I see in the `test/scope/*.html` files it seems that nothing is automated.
Should I setup some automation (with whichever test framework you want) or do I just add new tests following the same format with console logs?

Thanks

**Comment by dperini** [comment] 2017-11-26 17:04
@rraziel well at the moment I believe the objective is to have something as quick as possible.
Obviously an automated testing suite is preferred but you have no obligation about that, it depends on the spare time you have for this.

Unfortunately the w3c web-platform-tests don't contain tests for this pseudo-class yet, not that I am aware of.

At this stage it is more important to have some test that shows if there are problems with the current implementation which could be a few console test. We can further improve that later.

Thank you for the help, highly appreciated.

**Comment by rraziel** [comment] 2017-11-26 18:24
Well, your library is useful and I depend on it in my own projects, so I'll just find the time 😉.
I assume it would make your life easier as well, so if that's ok with you would:

1) submit a first PR that that adds jest (let me know if you prefer another one) and looks for *.spec.js files
2) submit a second PR that defines tests for `:scope`
3) submit a third PR for travis/circle/appveyor so that the project gets some CI as well

Note that for the 3rd one you'd need to sign up and authorize access to the repository to those services (and you might not want all 3).

If you'd rather have me just adding extra tests using the current setup, I can do that as well, obviously.

**Comment by dperini** [comment] 2017-11-26 21:17
@rraziel as I said it is up to you, your needs and your available time.
Personally I would prefer just 5/10 selected tests, possibly picked from the most representative, using the console to log passed/failed. This will prioritize a possible port of the ":scope" pseudo-class to "nwmatcher" which could be immediate if the outcome is positive.
As an example of the doubts I still have on this pseudo-class, I have a question for which you may have an answer: from what I have read on the related spec I understand that the ":scope" pseudo-class may only appear at the start of the selector string, is that true or false ?

**Comment by rraziel** [comment] 2017-11-27 01:22
Alright, then I'll start with PR number 2 and if you're interested I'll do 1&3 afterwards.

Regarding your doubts, I can't say I have much more information, especially considering the spec is basically 3 lines of text.

What I can say though is that (with the browsers I tested):
- `:scope` (alone) is valid syntax, returns null (would make sense to return the element but oh well...)
- `:scope something` is valid syntax, returns what is expected
- `something :scope` is valid syntax, returns null (I assume you're not supposed to walk up the ancestors)

**Comment by rraziel** [comment] 2017-11-27 01:26
And with some extra test:

```html
<div>
<ul>
<li></li>
</ul>
</div>
```

```javascript
document.querySelector('ul').querySelector('div > :scope > li');  // returns the li
document.querySelector('ul').querySelector('span > :scope > li'); // returns null
```

So what's before the `:scope` is also tested against (again, that's what the browser does, does not mean it's what the specification requires).

**Comment by dperini** [comment] 2017-11-27 02:04
@rraziel here are links to the documentation/specifications I am reading/following about ":scope":

    https://www.w3.org/TR/css-scoping-1/
and the editor’s draft link atop the reference list:

    http://dev.w3.org/csswg/css-scoping/
I believe the 3 lines you are referring to are the ones at this location:

    https://www.w3.org/TR/selectors4/#the-scope-pseudo
Just to be sure we have the same references and that we read the same docs/spec. :9)
Thank you again for the help you can give with this task and for your quick answer.

**Comment by dperini** [comment] 2017-11-30 15:03
@rraziel just to let you know so you  don't loose time trusting current results.
There are problems with the current implementation of the ":scope" pseudo-class.
I am working on that and doing more testing with some tests I found on the links above.

**Comment by rraziel** [comment] 2017-11-30 15:17
Well I had planned to do all this this week-end, so if you can by any chance commit your chances by then, it would be swell ;)

**Comment by dperini** [comment] 2017-12-04 15:42
@rraziel unfortunately I couldn't do that for the weekend sorry.
However now I fixed the incongruence I noticed and it should resolve the pseudo-class as expected.

**Comment by dperini** [comment] 2018-03-05 09:01
No news on this ... so I am closing the issue now, I have a few working test passing.
Feel free to reopen if you find new issues with the ":scope" pseudo-class.

**Closed by dperini** 2018-03-05 09:01 UTC

**Comment by angelfraga** [comment] 2021-02-12 10:30
Hi @dperini, I would like to re-open that issue.

I've found during my angular component test with Jest there is an edge case. 

It seems to fail selectors such  `:scope > .selector-a , :scope > .selector-b` 
While `:scope > .selector-a` or `:scope > .selector-b`   work fine.

In my case I would like to pick both element types in the right order, therefore I need to use comma. 

```html
<parent-element>
   <child-type-a></child-type-a>
   <child-type-b>
          <child-type-a></child-type-a>
          <child-type-a></child-type-a>
          <child-type-a></child-type-a>
          <child-type-b>
             <child-type-a></child-type-a>
              <child-type-a></child-type-a>
          </child-type-b>
   </child-type-b>
</parent-element>
```

If it is not a bug, Do you have any suggestion how to achieve that ?
